import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.net.InetSocketAddress;
import java.net.URI;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

// Servidor HTTP con JDBC. Java realiza API, SQL, validaciones y actas; JS solo usa fetch e interfaz.
public class ServidorJava {
    private static final Path RAIZ = Path.of("").toAbsolutePath().normalize();
    public static void main(String[] args) throws IOException {
        int puerto = args.length > 0 ? Integer.parseInt(args[0]) : 8080;
        HttpServer servidor = HttpServer.create(new InetSocketAddress(puerto), 0);
        servidor.createContext("/", ServidorJava::atender);
        servidor.setExecutor(null);
        servidor.start();
        System.out.println("ADDJ MOTORS disponible en http://localhost:" + puerto);
    }

    private static void atender(HttpExchange e) throws IOException {
        try {
            String ruta = e.getRequestURI().getPath();
            if (ruta.startsWith("/api/")) api(e, ruta);
            else archivo(e, ruta);
        } catch (IllegalArgumentException ex) { json(e, 400, Map.of("error", ex.getMessage()));
        } catch (SQLException ex) { json(e, 500, Map.of("error", "Error de base de datos: " + ex.getMessage()));
        } catch (Exception ex) { json(e, 500, Map.of("error", ex.getMessage() == null ? "Error interno" : ex.getMessage())); }
    }

    private static void api(HttpExchange e, String ruta) throws Exception {
        String metodo = e.getRequestMethod(); Map<String,String> q = parametros(e.getRequestURI());
        if (ruta.equals("/api/clientes")) {
            if (metodo.equals("GET")) { String estado=q.getOrDefault("estado","activos"); String condicion=estado.equals("todos")?"1=1":estado.equals("inactivos")?"activo=0":"activo=1"; json(e,200,consulta("SELECT * FROM clientes WHERE "+condicion+" ORDER BY nombre_completo")); return; }
            if (metodo.equals("POST")) { Map<String,Object>d=cuerpo(e); validarCliente(d); int id=insertar("INSERT INTO clientes(nombre_completo,domicilio,correo_electronico,telefono) VALUES(?,?,?,?)", JsonUtil.cadena(d,"nombreCompleto"),JsonUtil.cadena(d,"domicilio"),JsonUtil.cadena(d,"correoElectronico"),JsonUtil.cadena(d,"telefono")); json(e,201,Map.of("id",id)); return; }
        }
        if (ruta.matches("/api/clientes/\\d+")) { int id=idFinal(ruta); if(metodo.equals("PUT")){Map<String,Object>d=cuerpo(e);validarCliente(d); ejecutar("UPDATE clientes SET nombre_completo=?,domicilio=?,correo_electronico=?,telefono=?,activo=1 WHERE id_cliente=?",JsonUtil.cadena(d,"nombreCompleto"),JsonUtil.cadena(d,"domicilio"),JsonUtil.cadena(d,"correoElectronico"),JsonUtil.cadena(d,"telefono"),id);json(e,200,Map.of("id",id));return;} if(metodo.equals("DELETE")){int n=numero("SELECT (SELECT COUNT(*) FROM vehiculos WHERE id_vendedor=?)+(SELECT COUNT(*) FROM ventas WHERE id_comprador=?)",id,id);if(n>0){ejecutar("UPDATE clientes SET activo=0 WHERE id_cliente=?",id);json(e,200,Map.of("mensaje","Cliente desactivado; se conserva su historial."));}else{ejecutar("DELETE FROM clientes WHERE id_cliente=?",id);json(e,200,Map.of("mensaje","Cliente eliminado."));}return;} }
        if (ruta.matches("/api/clientes/\\d+/reactivar") && metodo.equals("POST")) { ejecutar("UPDATE clientes SET activo=1 WHERE id_cliente=?",idSegmento(ruta,3)); json(e,200,Map.of("mensaje","Cliente reactivado.")); return; }

        if (ruta.equals("/api/vehiculos")) {
            if(metodo.equals("GET")){json(e,200,vehiculos(q,false));return;}
            if(metodo.equals("POST")){Map<String,Object>d=cuerpo(e);int id=guardarVehiculo(d,0);json(e,201,Map.of("id",id));return;}
        }
        if(ruta.matches("/api/vehiculos/\\d+")){int id=idFinal(ruta);if(metodo.equals("GET")){List<Map<String,Object>>r=consulta("SELECT v.*,c.nombre_completo vendedor FROM vehiculos v JOIN clientes c ON c.id_cliente=v.id_vendedor WHERE id_vehiculo=?",id);if(r.isEmpty())throw new IllegalArgumentException("Vehículo no encontrado.");json(e,200,r.get(0));return;}if(metodo.equals("PUT")){if("VENDIDO".equals(textoUnico("SELECT estado FROM vehiculos WHERE id_vehiculo=?",id)))throw new IllegalArgumentException("No se puede editar un vehículo vendido.");guardarVehiculo(cuerpo(e),id);json(e,200,Map.of("id",id));return;}if(metodo.equals("DELETE")){if("VENDIDO".equals(textoUnico("SELECT estado FROM vehiculos WHERE id_vehiculo=?",id)))throw new IllegalArgumentException("No se puede eliminar un vehículo vendido.");ejecutar("DELETE FROM vehiculos WHERE id_vehiculo=?",id);json(e,200,Map.of("mensaje","Vehículo eliminado."));return;}}
        if(ruta.matches("/api/vehiculos/\\d+/estado")&&metodo.equals("PUT")){int id=idSegmento(ruta,3);Map<String,Object>d=cuerpo(e);String nuevo=JsonUtil.cadena(d,"estado");if(!nuevo.equals("PUBLICADO")&&!nuevo.equals("APARTADO"))throw new IllegalArgumentException("Estado inválido.");String anterior=textoUnico("SELECT estado FROM vehiculos WHERE id_vehiculo=?",id);if(anterior==null||anterior.equals("VENDIDO"))throw new IllegalArgumentException("No se puede cambiar el estado.");ejecutar("UPDATE vehiculos SET estado=? WHERE id_vehiculo=?",nuevo,id);historial("VEHICULO",id,anterior,nuevo,JsonUtil.cadena(d,"motivo"));json(e,200,Map.of("mensaje","Estado actualizado."));return;}

        if(ruta.equals("/api/ventas")&&metodo.equals("POST")){json(e,201,registrarVenta(cuerpo(e)));return;}
        if(ruta.matches("/api/ventas/\\d+/abonos")){int id=idSegmento(ruta,3);if(metodo.equals("GET")){json(e,200,consulta("SELECT * FROM abonos_venta WHERE id_venta=? ORDER BY fecha_abono DESC,id_abono DESC",id));return;}if(metodo.equals("POST")){Map<String,Object>d=cuerpo(e);BigDecimal monto=JsonUtil.decimal(d,"monto");Map<String,Object>v=consulta("SELECT precio_final,estatus_pago,estado_venta,COALESCE((SELECT SUM(monto) FROM abonos_venta WHERE id_venta=ventas.id_venta),0) abonado FROM ventas WHERE id_venta=?",id).get(0);if("CANCELADA".equals(v.get("estado_venta"))||"PAGADO".equals(v.get("estatus_pago")))throw new IllegalArgumentException("No se pueden agregar abonos a esta venta.");BigDecimal total=(BigDecimal)v.get("abonado");BigDecimal precio=(BigDecimal)v.get("precio_final");if(total.add(monto).compareTo(precio)>0)throw new IllegalArgumentException("El abono supera el precio final.");ejecutar("INSERT INTO abonos_venta(id_venta,monto,metodo_pago,referencia_pago,observaciones) VALUES(?,?,?,?,?)",id,monto,valor(d,"metodoPago","EFECTIVO"),JsonUtil.cadena(d,"referenciaPago"),JsonUtil.cadena(d,"observaciones"));if(total.add(monto).compareTo(precio)>=0)ejecutar("UPDATE ventas SET estatus_pago='PAGADO' WHERE id_venta=?",id);json(e,201,Map.of("mensaje","Abono registrado.","saldo",precio.subtract(total.add(monto))));return;}}
        if(ruta.matches("/api/ventas/\\d+/cancelar")&&metodo.equals("POST")){int id=idSegmento(ruta,3);List<Map<String,Object>>v=consulta("SELECT * FROM ventas WHERE id_venta=?",id);if(v.isEmpty())throw new IllegalArgumentException("Venta no encontrada.");ejecutar("UPDATE ventas SET estado_venta='CANCELADA' WHERE id_venta=?",id);ejecutar("UPDATE vehiculos SET estado='PUBLICADO' WHERE id_vehiculo=?",v.get(0).get("id_vehiculo"));historial("VENTA",id,"ACTIVA","CANCELADA","Cancelación de venta");json(e,200,Map.of("mensaje","Venta cancelada."));return;}
        if(ruta.matches("/api/ventas/\\d+/estatus")&&metodo.equals("PUT")){int id=idSegmento(ruta,3);Map<String,Object>d=cuerpo(e);String nuevo=JsonUtil.cadena(d,"estatusPago");String anterior=textoUnico("SELECT estatus_pago FROM ventas WHERE id_venta=?",id);ejecutar("UPDATE ventas SET estatus_pago=? WHERE id_venta=?",nuevo,id);historial("PAGO",id,anterior,nuevo,valor(d,"motivo","Cambio manual"));json(e,200,Map.of("mensaje","Estatus actualizado."));return;}
        if(ruta.matches("/api/ventas/\\d+/acta")&&metodo.equals("POST")){int id=idSegmento(ruta,3);String acta=generarActa(id);json(e,200,Map.of("mensaje","Acta generada.","acta",acta));return;}

        if(ruta.equals("/api/reportes/ofertas")&&metodo.equals("GET")){json(e,200,vehiculos(q,true));return;}
        if(ruta.equals("/api/reportes/vendidos")&&metodo.equals("GET")){json(e,200,consulta("SELECT ven.*,v.*,cv.nombre_completo vendedor,cc.nombre_completo comprador,COALESCE((SELECT SUM(monto) FROM abonos_venta a WHERE a.id_venta=ven.id_venta),0) monto_pagado FROM ventas ven JOIN vehiculos v ON v.id_vehiculo=ven.id_vehiculo JOIN clientes cv ON cv.id_cliente=v.id_vendedor JOIN clientes cc ON cc.id_cliente=ven.id_comprador ORDER BY ven.fecha_venta DESC"));return;}
        if(ruta.equals("/api/reportes/estadisticas")&&metodo.equals("GET")){json(e,200,consulta("SELECT COUNT(*) total_vehiculos,SUM(estado='PUBLICADO') vehiculos_activos,SUM(estado='VENDIDO') vehiculos_vendidos,COALESCE((SELECT SUM(precio_final) FROM ventas WHERE estado_venta='ACTIVA'),0) ingresos_totales FROM vehiculos").get(0));return;}
        json(e,404,Map.of("error","Ruta no encontrada."));
    }

    private static List<Map<String,Object>> vehiculos(Map<String,String> q,boolean ofertas) throws SQLException {StringBuilder s=new StringBuilder("SELECT v.*,c.nombre_completo vendedor FROM vehiculos v JOIN clientes c ON c.id_cliente=v.id_vendedor WHERE 1=1");List<Object>p=new ArrayList<>();if(ofertas)s.append(" AND v.estado IN ('PUBLICADO','APARTADO')");filtro(s,p,q,"modelo","v.modelo=?");filtro(s,p,q,"marca","v.marca LIKE ?",true);filtro(s,p,q,"precio","v.precio_venta=?");filtro(s,p,q,"fecha","DATE(v.fecha_publicacion)=?");s.append(" ORDER BY v.fecha_publicacion DESC");return consulta(s.toString(),p.toArray());}
    private static void filtro(StringBuilder s,List<Object>p,Map<String,String>q,String k,String sql){filtro(s,p,q,k,sql,false);} private static void filtro(StringBuilder s,List<Object>p,Map<String,String>q,String k,String sql,boolean like){if(q.containsKey(k)&&!q.get(k).isBlank()){s.append(" AND ").append(sql);p.add(like?"%"+q.get(k)+"%":q.get(k));}}
    private static int guardarVehiculo(Map<String,Object>d,int id) throws SQLException {String[]k={"idVendedor","numeroMotor","numeroSerie","modelo","marca","linea","color","precioCompra","precioVenta","transmision","numeroCilindros","nacionalidad","descripcion"};for(String x:k)if(JsonUtil.cadena(d,x).isBlank())throw new IllegalArgumentException("Falta el dato: "+x);Object[]p={JsonUtil.entero(d,"idVendedor"),JsonUtil.cadena(d,"numeroMotor"),JsonUtil.cadena(d,"numeroSerie"),JsonUtil.entero(d,"modelo"),JsonUtil.cadena(d,"marca"),JsonUtil.cadena(d,"linea"),JsonUtil.cadena(d,"color"),JsonUtil.decimal(d,"precioCompra"),JsonUtil.decimal(d,"precioVenta"),JsonUtil.cadena(d,"transmision"),JsonUtil.entero(d,"numeroCilindros"),JsonUtil.cadena(d,"nacionalidad"),JsonUtil.cadena(d,"descripcion"),JsonUtil.cadena(d,"observaciones"),JsonUtil.cadena(d,"urlImagen")};if(id==0)return insertar("INSERT INTO vehiculos(id_vendedor,numero_motor,numero_serie,modelo,marca,linea,color,precio_compra,precio_venta,transmision,numero_cilindros,nacionalidad,descripcion,observaciones,url_imagen) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",p);Object[]u=new Object[p.length+1];System.arraycopy(p,0,u,0,p.length);u[p.length]=id;ejecutar("UPDATE vehiculos SET id_vendedor=?,numero_motor=?,numero_serie=?,modelo=?,marca=?,linea=?,color=?,precio_compra=?,precio_venta=?,transmision=?,numero_cilindros=?,nacionalidad=?,descripcion=?,observaciones=?,url_imagen=? WHERE id_vehiculo=?",u);return id;}
    private static Map<String,Object> registrarVenta(Map<String,Object>d) throws Exception {int veh=JsonUtil.entero(d,"idVehiculo"),comprador=JsonUtil.entero(d,"idComprador");BigDecimal precio=JsonUtil.decimal(d,"precioFinal");try(Connection c=ConfiguracionBD.abrir()){c.setAutoCommit(false);try{Map<String,Object>v=consulta(c,"SELECT * FROM vehiculos WHERE id_vehiculo=? FOR UPDATE",veh).get(0);if("VENDIDO".equals(v.get("estado")))throw new IllegalArgumentException("Vehículo ya vendido.");if(((Number)v.get("id_vendedor")).intValue()==comprador)throw new IllegalArgumentException("Comprador y vendedor deben ser diferentes.");int id;try(PreparedStatement ps=c.prepareStatement("INSERT INTO ventas(id_vehiculo,id_comprador,precio_final,estatus_pago,estado_venta) VALUES(?,?,?,?, 'ACTIVA')",Statement.RETURN_GENERATED_KEYS)){ps.setInt(1,veh);ps.setInt(2,comprador);ps.setBigDecimal(3,precio);ps.setString(4,valor(d,"estatusPago","PAGADO"));ps.executeUpdate();try(ResultSet rs=ps.getGeneratedKeys()){rs.next();id=rs.getInt(1);}}ejecutar(c,"UPDATE ventas SET folio_venta=? WHERE id_venta=?","VTA-"+String.format("%05d",id),id);ejecutar(c,"UPDATE vehiculos SET estado='VENDIDO' WHERE id_vehiculo=?",veh);historial(c,"VENTA",id,null,"ACTIVA","Registro de venta");c.commit();String acta=generarActa(id);return Map.of("mensaje","Venta registrada.","acta",acta);}catch(Exception x){c.rollback();throw x;}finally{c.setAutoCommit(true);}}}
    private static String generarActa(int id)throws Exception{Map<String,Object>r=consulta("SELECT ven.*,v.*,cv.nombre_completo vendedor,cv.domicilio domicilio_vendedor,cv.correo_electronico correo_vendedor,cv.telefono telefono_vendedor,cc.nombre_completo comprador,cc.domicilio domicilio_comprador,cc.correo_electronico correo_comprador,cc.telefono telefono_comprador FROM ventas ven JOIN vehiculos v ON v.id_vehiculo=ven.id_vehiculo JOIN clientes cv ON cv.id_cliente=v.id_vendedor JOIN clientes cc ON cc.id_cliente=ven.id_comprador WHERE ven.id_venta=?",id).get(0);String f="acta-venta-"+id+"-"+System.currentTimeMillis()+".html";GeneradorActa.main(new String[]{String.valueOf(r.get("id_vehiculo")),""+r.get("numero_motor"),""+r.get("numero_serie"),""+r.get("modelo"),""+r.get("marca"),""+r.get("linea"),""+r.get("color"),""+r.get("precio_compra"),""+r.get("precio_final"),""+r.get("transmision"),""+r.get("numero_cilindros"),""+r.get("nacionalidad"),""+r.get("descripcion"),""+r.get("observaciones"),""+r.get("vendedor"),""+r.get("domicilio_vendedor"),""+r.get("correo_vendedor"),""+r.get("telefono_vendedor"),""+r.get("comprador"),""+r.get("domicilio_comprador"),""+r.get("correo_comprador"),""+r.get("telefono_comprador"),"Morelia, Michoacán.",LocalDate.now().toString(),f});String ruta="/actas/"+f;ejecutar("UPDATE ventas SET ruta_acta=? WHERE id_venta=?",ruta,id);return ruta;}
    private static void validarCliente(Map<String,Object>d){for(String k:new String[]{"nombreCompleto","domicilio","correoElectronico","telefono"})if(JsonUtil.cadena(d,k).isBlank())throw new IllegalArgumentException("Falta el dato: "+k);}
    private static String valor(Map<String,Object>d,String k,String def){String v=JsonUtil.cadena(d,k);return v.isBlank()?def:v;}
    private static void historial(String e,int id,String a,String n,String m)throws SQLException{try(Connection c=ConfiguracionBD.abrir()){historial(c,e,id,a,n,m);}} private static void historial(Connection c,String e,int id,String a,String n,String m)throws SQLException{ejecutar(c,"INSERT INTO historial_estados(entidad,id_entidad,estado_anterior,estado_nuevo,motivo) VALUES(?,?,?,?,?)",e,id,a,n,m);}
    private static List<Map<String,Object>> consulta(String s,Object...p)throws SQLException{try(Connection c=ConfiguracionBD.abrir()){return consulta(c,s,p);}} private static List<Map<String,Object>> consulta(Connection c,String s,Object...p)throws SQLException{try(PreparedStatement ps=c.prepareStatement(s)){for(int i=0;i<p.length;i++)ps.setObject(i+1,p[i]);try(ResultSet rs=ps.executeQuery()){List<Map<String,Object>>l=new ArrayList<>();ResultSetMetaData md=rs.getMetaData();while(rs.next()){Map<String,Object>m=new LinkedHashMap<>();for(int i=1;i<=md.getColumnCount();i++)m.put(md.getColumnLabel(i),rs.getObject(i));l.add(m);}return l;}}}
    private static void ejecutar(String s,Object...p)throws SQLException{try(Connection c=ConfiguracionBD.abrir()){ejecutar(c,s,p);}}private static void ejecutar(Connection c,String s,Object...p)throws SQLException{try(PreparedStatement ps=c.prepareStatement(s)){for(int i=0;i<p.length;i++)ps.setObject(i+1,p[i]);ps.executeUpdate();}}private static int insertar(String s,Object...p)throws SQLException{try(Connection c=ConfiguracionBD.abrir();PreparedStatement ps=c.prepareStatement(s,Statement.RETURN_GENERATED_KEYS)){for(int i=0;i<p.length;i++)ps.setObject(i+1,p[i]);ps.executeUpdate();try(ResultSet rs=ps.getGeneratedKeys()){rs.next();return rs.getInt(1);}}}private static int numero(String s,Object...p)throws SQLException{return ((Number)consulta(s,p).get(0).values().iterator().next()).intValue();}private static String textoUnico(String s,Object...p)throws SQLException{List<Map<String,Object>>r=consulta(s,p);return r.isEmpty()?null:String.valueOf(r.get(0).values().iterator().next());}
    private static Map<String,Object> cuerpo(HttpExchange e)throws IOException{return JsonUtil.objeto(new String(e.getRequestBody().readAllBytes(),StandardCharsets.UTF_8));}private static int idFinal(String r){return Integer.parseInt(r.substring(r.lastIndexOf('/')+1));}private static int idSegmento(String r,int n){return Integer.parseInt(r.split("/")[n]);}private static Map<String,String> parametros(URI u){Map<String,String>m=new LinkedHashMap<>();String q=u.getRawQuery();if(q==null)return m;for(String x:q.split("&")){String[]p=x.split("=",2);m.put(URLDecoder.decode(p[0],StandardCharsets.UTF_8),p.length>1?URLDecoder.decode(p[1],StandardCharsets.UTF_8):"");}return m;}
    private static void json(HttpExchange e,int s,Object d)throws IOException{byte[]b=JsonUtil.texto(d).getBytes(StandardCharsets.UTF_8);e.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");e.sendResponseHeaders(s,b.length);e.getResponseBody().write(b);e.close();}
    private static void archivo(HttpExchange e,String ruta)throws IOException{if(ruta.equals("/"))ruta="/frontend/index.html";else if(!ruta.startsWith("/frontend/")&&!ruta.startsWith("/actas/"))ruta="/frontend"+ruta;Path f=RAIZ.resolve(ruta.substring(1)).normalize();if(!f.startsWith(RAIZ)||!Files.exists(f)){json(e,404,Map.of("error","Archivo no encontrado."));return;}String tipo=ruta.endsWith(".html")?"text/html":ruta.endsWith(".css")?"text/css":ruta.endsWith(".js")?"application/javascript":ruta.endsWith(".svg")?"image/svg+xml":"application/octet-stream";byte[]b=Files.readAllBytes(f);e.getResponseHeaders().set("Content-Type",tipo+"; charset=utf-8");e.sendResponseHeaders(200,b.length);e.getResponseBody().write(b);e.close();}
}
